import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Masthead from '../components/masthead'
import About from '../components/about'
import Skills from '../components/skills'
import Works from '../components/works'
import Trusted from '../components/trusted'
import Footer from '../components/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Plasm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <About />
      <Skills />
      <Works />
      <Trusted />
      <Footer />
    </div>
  )
}

export default Home
